### ISSUE TITLE
Text Q&A For Poster

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana-ohbm-2020#1]
Unfortunately when you close out the chat for our poster's meeting link, all text goes away, meaning there is no way to continue conversation conveniently. @handwerkerd and I propose that we make a globally writable Google Doc for people to put their questions in and for people to answer over the course of OHBM (particularly during the scheduled poster time). We could moderate it over the course of the conference, and then lock it at the end. Furthermore, this would let us record what questions people had for future reference, similar to how in the past we've kept minutes for multi-echo discussions at OHBM.

Please thumbs-up if you approve of the plan. Please thumbs-down and leave a comment explaining why if you disapprove.

**Comment by handwerkerd** [comment]
After talking with @jbteves my current plan is to have to places to receive feedback:
https://meet.jit.si/ohbm-poster-1083 for live chats during poster sessions.
https://bit.ly/2Z1T8Xl is a world-commentable google doc that we'd monitor & lock down after OHBM.

I'd put both of those links in the README.md for this repository and I'd alert all poster authors so, if anyone is contacted, they know where to direct people.

Does this sound reasonable to others directly involved with OHBM?
@emdupre @tsalo @smoia @javiergcas

**Comment by handwerkerd** [comment]
Also for getting feedback, I'm planning to be present for (NY time zone) 1:00PM on 6/24. Perhaps some of 9:00PM on 6/26 &  9:00PM on 6/30. I don't plan to attend at 3:00AM on July 2. I welcome others to share responsibilities for the first three days. For July 2, we can either not have live response or perhaps a European may volunteer.

**Comment by handwerkerd** [comment]
Yaroslav set up a list of jit.si addresses for every poster: https://twitter.com/yarikoptic/status/1275645482946215941 He lists ours as: https://meet.jit.si/ohbm2020-1083 I'm going to update the link on this site now. If people contact you during poster hours, direct them to that site. You are also welcome to join in and say hello as well.

**Comment by jbteves** [comment]
I can attend today at 1 PM and tentatively Friday at 9 PM. I also will not stay up until 3 AM+ on July 2, because even if I'm awake I likely won't be awake enough to discuss the finer points of FOSS or multi-echo.
